# Generated by Django 4.2.24 on 2025-09-17 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_malicious', models.BooleanField(default=False)),
                ('confidence_percentage', models.IntegerField(default=0)),
                ('abuse_confidence', models.IntegerField(default=0)),
                ('usage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('threat_types', models.JSONField(blank=True, default=list)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_api', models.CharField(default='abuseipdb', max_length=50)),
            ],
            options={
                'db_table': 'threat_intelligence',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_threats', models.IntegerField(default=0)),
                ('new_threats', models.IntegerField(default=0)),
                ('high_confidence_threats', models.IntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
                ('threat_type_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'threat_statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threat_intelligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='threat_intelligence.threatintelligence')),
            ],
            options={
                'db_table': 'threat_events',
                'ordering': ['-detected_at'],
            },
        ),
    ]
