# Generated by Django 4.2.23 on 2025-08-26 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scan_type', models.CharField(choices=[('pcap', 'PCAP Analysis'), ('live', 'Live Capture'), ('netlog', 'Network Log')], default='pcap', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_packets', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('suspicious_connections', models.IntegerField(default=0)),
                ('malicious_domains', models.IntegerField(default=0)),
                ('threat_score', models.FloatField(default=0.0)),
                ('ai_analysis_complete', models.BooleanField(default=False)),
                ('ai_threat_prediction', models.JSONField(default=dict)),
                ('ai_recommendations', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='NetworkStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_file_scans', models.IntegerField(default=0)),
                ('total_network_scans', models.IntegerField(default=0)),
                ('total_packets_analyzed', models.BigIntegerField(default=0)),
                ('malicious_ips_detected', models.IntegerField(default=0)),
                ('suspicious_domains_detected', models.IntegerField(default=0)),
                ('botnet_communications', models.IntegerField(default=0)),
                ('ai_predictions_made', models.IntegerField(default=0)),
                ('ai_accuracy_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('threat_level', models.CharField(choices=[('clean', 'Clean'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='clean', max_length=20)),
                ('scan_duration', models.FloatField(blank=True, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ScanStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('clean_files', models.IntegerField(default=0)),
                ('infected_files', models.IntegerField(default=0)),
                ('total_threats', models.IntegerField(default=0)),
                ('avg_scan_duration', models.FloatField(default=0.0)),
                ('total_file_size', models.BigIntegerField(default=0)),
                ('virus_count', models.IntegerField(default=0)),
                ('malware_count', models.IntegerField(default=0)),
                ('ransomware_count', models.IntegerField(default=0)),
                ('trojan_count', models.IntegerField(default=0)),
                ('spyware_count', models.IntegerField(default=0)),
                ('adware_count', models.IntegerField(default=0)),
                ('worm_count', models.IntegerField(default=0)),
                ('rootkit_count', models.IntegerField(default=0)),
                ('backdoor_count', models.IntegerField(default=0)),
                ('exploit_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YaraRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rule_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yara_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanThreat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('threat_type', models.CharField(choices=[('virus', 'Virus'), ('malware', 'Malware'), ('ransomware', 'Ransomware'), ('trojan', 'Trojan'), ('spyware', 'Spyware'), ('adware', 'Adware'), ('worm', 'Worm'), ('rootkit', 'Rootkit'), ('backdoor', 'Backdoor'), ('exploit', 'Exploit'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('detection_engine', models.CharField(max_length=50)),
                ('detection_rule', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('clean', 'Clean'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('scan_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='scanner.scanresult')),
            ],
            options={
                'ordering': ['-severity'],
            },
        ),
        migrations.CreateModel(
            name='NetworkThreat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_category', models.CharField(choices=[('malicious_ip', 'Malicious IP'), ('suspicious_domain', 'Suspicious Domain'), ('botnet', 'Botnet Communication'), ('data_exfil', 'Data Exfiltration'), ('c2', 'Command & Control'), ('port_scan', 'Port Scanning'), ('ddos', 'DDoS Attack'), ('protocol_anomaly', 'Protocol Anomaly'), ('encrypted_tunnel', 'Suspicious Encrypted Tunnel')], max_length=30)),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('destination_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=10)),
                ('threat_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('clean', 'Clean'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('packet_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('source_country', models.CharField(blank=True, max_length=2)),
                ('destination_country', models.CharField(blank=True, max_length=2)),
                ('network_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_threats', to='scanner.networkscan')),
            ],
            options={
                'ordering': ['-severity', '-confidence_score'],
            },
        ),
    ]
