# Generated by Django 4.2.24 on 2025-09-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkscan',
            name='user',
        ),
        migrations.DeleteModel(
            name='NetworkStatistics',
        ),
        migrations.RemoveField(
            model_name='networkthreat',
            name='network_scan',
        ),
        migrations.DeleteModel(
            name='NetworkScan',
        ),
        migrations.DeleteModel(
            name='NetworkThreat',
        ),
    ]
