# Generated by Django 4.2.24 on 2025-09-17 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scanner', '0002_remove_networkscan_user_delete_networkstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalThreatStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_threats', models.IntegerField(default=0)),
                ('malware_count', models.IntegerField(default=0)),
                ('virus_count', models.IntegerField(default=0)),
                ('ransomware_count', models.IntegerField(default=0)),
                ('trojan_count', models.IntegerField(default=0)),
                ('spyware_count', models.IntegerField(default=0)),
                ('adware_count', models.IntegerField(default=0)),
                ('worm_count', models.IntegerField(default=0)),
                ('rootkit_count', models.IntegerField(default=0)),
                ('backdoor_count', models.IntegerField(default=0)),
                ('exploit_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('low_severity_count', models.IntegerField(default=0)),
                ('medium_severity_count', models.IntegerField(default=0)),
                ('high_severity_count', models.IntegerField(default=0)),
                ('critical_severity_count', models.IntegerField(default=0)),
                ('country_distribution', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Global Threat Statistics',
                'verbose_name_plural': 'Global Threat Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('threat_type', models.CharField(choices=[('malware', 'Malware'), ('virus', 'Virus'), ('ransomware', 'Ransomware'), ('trojan', 'Trojan'), ('spyware', 'Spyware'), ('adware', 'Adware'), ('worm', 'Worm'), ('rootkit', 'Rootkit'), ('backdoor', 'Backdoor'), ('exploit', 'Exploit'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('scan_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_events', to='scanner.scanresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
