# Generated by Django 4.2.23 on 2025-08-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification_alter_user_last_login'),
        ('users', '0002_user_job_title_user_organization_user_phone_number_and_more'),
    ]

    operations = [
    ]
