# Generated by Django 4.2.24 on 2025-09-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250824_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
